# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

export EDITOR='vim'
alias mux="tmuxinator"

# tmux - set 10ms for key sequences
export KEYTIMEOUT=10

export HISTSIZE=10000
export SAVEHIST=10000

#xrdb ~/.Xresources
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

alias fullscreen="wmctrl -r :ACTIVE: -b toggle,fullscreen"
